---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sayalideployment

spec:
 template:
   metadata:
      name: sayalipod
      labels:
        app: sayaliapp      
   spec:
     containers:
       - name: nginx-container
         image: nginx
 replicas: 5
 
 selector:
   matchLabels:
     app: sayaliapp
...
