---
- name: Configuring APACHE 2 remotely using automation
  hosts: all
  tasks:
    - name: Installing APACHE 2 server
      apt:
        name: apache2
        state: present
    - name: Editing the index file
      copy:
        dest: /var/www/html/index.html
        content: "This is my automate webserver"
    - name: Change the port from 80 to 81
      lineinfile:
        path: /etc/apache2/ports.conf
        regex: '^Listen 80'
        line: 'Listen 81'
        backrefs: yes
      notify:
        - start the apache
  handlers:
    - name: start the apache
      service:
        name: apache2
        state: started
...
